# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-GB"
title                    : "Aneirin John Baker"
title_separator          : "-"
subtitle                 : "Version 1.0"
name                     : "Aneirin Baker"
description              : "A website for me to mess around on"

breadcrumbs              : false
words_per_minute         : 200

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-remote-theme

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true 



  provider               : "google" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : UA-186306170-1
    anonymize_ip         : false # true, false (default)


# Site Author
author:
  name             : Aneirin Baker
  avatar           : /assets/img/AboutMe/Pic_of_me.jpg
  bio: 
    PhD Researcher
    <br> 
    Superconducting Circuits
    
  links:
    - label: "Edinburgh UK"
      icon: "fas fa-2x fa-fw fa-map-marker-alt"
      url: "https://www.lunduniversity.lu.se/lucat/user/103e4b4ed2f6ea7e498de3c28157c7bd/"
    - label: "Email"
      icon: "fas fa-2x fa-fw fa-envelope"
      url: "mailto:ajb17 [at] hw.ac.uk"
    - label: "Twitter"
      icon: "fab fa-2x fa-fw fa-twitter"
      url: "https://twitter.com/BakerNye"
    - label: "GitHub"
      icon: "fab fa-2x fa-fw fa-github"
      url: "https://github.com/nyeBaker"
      
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BakerNye"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/nyeBaker"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/aneirin-baker/"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn

  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false

scholar:
  style: modern-language-association